services:
    add_film_use_case:
        class: FilmApiBundle\Service\AddFilmUseCase
        arguments: ["@film_repository"]

    film_repository:
        class: FilmApiBundle\Repository\FilmRepository
        factory:
          - "@doctrine.orm.default_entity_manager"
          - "getRepository"
        arguments:
          - "FilmApiBundle:Film"