FilmApiBundle\Entity\Film:
  type: entity
  repositoryClass: FilmApiBundle\Repository\FilmRepository
  table: film
  id:
    id:
      type: string
  fields:
    name:
      type: string
    year:
      type: smallint
    date:
      type: datetime
    url:
      type: string